[package]
name = "dexs"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
no-entrypoint = []
std = []

[dependencies]
pinocchio = { workspace = true }
pinocchio-log = { workspace = true }
pinocchio-pubkey = { workspace = true }
pinocchio-system = { workspace = true }
bytemuck = { workspace = true }
shank = { workspace = true }

pinocchio-helper = { path = "../../pinocchio-helper" }

[dev-dependencies]
tokio = { workspace = true }
mollusk-svm = { workspace = true }
solana-sdk = { workspace = true }
solana-program-runtime = { workspace = true }
solana-client = { workspace = true }
spl-token = { workspace = true }
spl-associated-token-account = { workspace = true }
